from StemProcess import stem_words

def write_file(teks,url):
    fo = open(url,"w")
    fo.write(teks)
    fo.close()

# stemming process
polstem=[]
ekostem=[]
pendstem=[]

print()
polstem.append("== POLITIK ==")
polstem.append(stem_words('dokumen/politik/politik1.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik2.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik3.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik4.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik5.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik6.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik7.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik8.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik9.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik10.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik11.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik12.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik13.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik14.txt',type="url"))
polstem.append(stem_words('dokumen/politik/politik15.txt',type="url"))

pol = "\n\n".join(polstem)
write_file(pol,"dokumen/polstem.txt")

ekostem.append("== EKONOMI ==")
ekostem.append(stem_words('dokumen/ekonomi/ek01.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek02.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek03.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek04.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek05.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek06.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek07.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek08.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek09.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek10.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek11.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek12.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek13.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek14.txt',type="url"))
ekostem.append(stem_words('dokumen/ekonomi/ek15.txt',type="url"))

eko = "\n\n".join(ekostem)
write_file(eko,"dokumen/ekostem.txt")

pendstem.append("== PENDIDIKAN ==")
pendstem.append(stem_words('dokumen/pendidikan/pend01.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend02.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend03.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend04.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend05.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend06.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend07.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend08.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend09.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend10.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend11.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend12.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend13.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend14.txt',type="url"))
pendstem.append(stem_words('dokumen/pendidikan/pend15.txt',type="url"))

pend = "\n\n".join(pendstem)
write_file(pend,"dokumen/pendstem.txt")

# stem_words('dokumen/politik/politik2.txt',type="url")
# stem_words('dokumen/politik/politik3.txt',type="url")
# stem_words('dokumen/politik/politik4.txt',type="url")
# stem_words('dokumen/politik/politik5.txt',type="url")
# stem_words('dokumen/politik/politik6.txt',type="url")
# stem_words('dokumen/politik/politik7.txt',type="url")
# stem_words('dokumen/politik/politik8.txt',type="url")
# stem_words('dokumen/politik/politik9.txt',type="url")
# stem_words('dokumen/politik/politik10.txt',type="url")
# stem_words('dokumen/politik/politik11.txt',type="url")
# stem_words('dokumen/politik/politik12.txt',type="url")
# stem_words('dokumen/politik/politik13.txt',type="url")
# stem_words('dokumen/politik/politik14.txt',type="url")
# stem_words('dokumen/politik/politik15.txt',type="url")
#
# print("== EKONOMI ==")
# stem_words('dokumen/ekonomi/ek01.txt',type="url")
# stem_words('dokumen/ekonomi/ek02.txt',type="url")
# stem_words('dokumen/ekonomi/ek03.txt',type="url")
# stem_words('dokumen/ekonomi/ek04.txt',type="url")
# stem_words('dokumen/ekonomi/ek05.txt',type="url")
# stem_words('dokumen/ekonomi/ek06.txt',type="url")
# stem_words('dokumen/ekonomi/ek07.txt',type="url")
# stem_words('dokumen/ekonomi/ek08.txt',type="url")
# stem_words('dokumen/ekonomi/ek09.txt',type="url")
# stem_words('dokumen/ekonomi/ek10.txt',type="url")
# stem_words('dokumen/ekonomi/ek11.txt',type="url")
# stem_words('dokumen/ekonomi/ek12.txt',type="url")
# stem_words('dokumen/ekonomi/ek13.txt',type="url")
# stem_words('dokumen/ekonomi/ek14.txt',type="url")
# stem_words('dokumen/ekonomi/ek15.txt',type="url")
#
# print("== PENDIDIKAN ==")
# stem_words('dokumen/pendidikan/pend01.txt',type="url")
# stem_words('dokumen/pendidikan/pend02.txt',type="url")
# stem_words('dokumen/pendidikan/pend03.txt',type="url")
# stem_words('dokumen/pendidikan/pend04.txt',type="url")
# stem_words('dokumen/pendidikan/pend05.txt',type="url")
# stem_words('dokumen/pendidikan/pend06.txt',type="url")
# stem_words('dokumen/pendidikan/pend07.txt',type="url")
# stem_words('dokumen/pendidikan/pend08.txt',type="url")
# stem_words('dokumen/pendidikan/pend09.txt',type="url")
# stem_words('dokumen/pendidikan/pend10.txt',type="url")
# stem_words('dokumen/pendidikan/pend11.txt',type="url")
# stem_words('dokumen/pendidikan/pend12.txt',type="url")
# stem_words('dokumen/pendidikan/pend13.txt',type="url")
# stem_words('dokumen/pendidikan/pend14.txt',type="url")
# stem_words('dokumen/pendidikan/pend15.txt',type="url")
